<?php

/*
|--------------------------------------------------------------------------
| Countries + dial codes
|--------------------------------------------------------------------------
| Shared reference list for client/lead forms (country name + phone dial code).
| Kept in sync with the website's composables/useCountries.ts. Popular first,
| then every other country alphabetically. Each entry: code, name, dial, flag.
|
| Flags for the "rest of the world" block are derived from the ISO alpha-2
| code (regional-indicator symbols), so only code + name + dial are listed.
*/

$popular = [
    ['code' => 'BD', 'name' => 'Bangladesh', 'dial' => '+880', 'flag' => '🇧🇩'],
    ['code' => 'US', 'name' => 'United States', 'dial' => '+1', 'flag' => '🇺🇸'],
    ['code' => 'GB', 'name' => 'United Kingdom', 'dial' => '+44', 'flag' => '🇬🇧'],
    ['code' => 'IN', 'name' => 'India', 'dial' => '+91', 'flag' => '🇮🇳'],
    ['code' => 'CA', 'name' => 'Canada', 'dial' => '+1', 'flag' => '🇨🇦'],
    ['code' => 'AU', 'name' => 'Australia', 'dial' => '+61', 'flag' => '🇦🇺'],
    ['code' => 'AE', 'name' => 'United Arab Emirates', 'dial' => '+971', 'flag' => '🇦🇪'],
    ['code' => 'SA', 'name' => 'Saudi Arabia', 'dial' => '+966', 'flag' => '🇸🇦'],
    ['code' => 'PK', 'name' => 'Pakistan', 'dial' => '+92', 'flag' => '🇵🇰'],
    ['code' => 'BR', 'name' => 'Brazil', 'dial' => '+55', 'flag' => '🇧🇷'],
    ['code' => 'CN', 'name' => 'China', 'dial' => '+86', 'flag' => '🇨🇳'],
    ['code' => 'DE', 'name' => 'Germany', 'dial' => '+49', 'flag' => '🇩🇪'],
    ['code' => 'EG', 'name' => 'Egypt', 'dial' => '+20', 'flag' => '🇪🇬'],
    ['code' => 'ES', 'name' => 'Spain', 'dial' => '+34', 'flag' => '🇪🇸'],
    ['code' => 'FR', 'name' => 'France', 'dial' => '+33', 'flag' => '🇫🇷'],
    ['code' => 'ID', 'name' => 'Indonesia', 'dial' => '+62', 'flag' => '🇮🇩'],
    ['code' => 'IT', 'name' => 'Italy', 'dial' => '+39', 'flag' => '🇮🇹'],
    ['code' => 'JP', 'name' => 'Japan', 'dial' => '+81', 'flag' => '🇯🇵'],
    ['code' => 'KR', 'name' => 'South Korea', 'dial' => '+82', 'flag' => '🇰🇷'],
    ['code' => 'KW', 'name' => 'Kuwait', 'dial' => '+965', 'flag' => '🇰🇼'],
    ['code' => 'LK', 'name' => 'Sri Lanka', 'dial' => '+94', 'flag' => '🇱🇰'],
    ['code' => 'MX', 'name' => 'Mexico', 'dial' => '+52', 'flag' => '🇲🇽'],
    ['code' => 'MY', 'name' => 'Malaysia', 'dial' => '+60', 'flag' => '🇲🇾'],
    ['code' => 'NG', 'name' => 'Nigeria', 'dial' => '+234', 'flag' => '🇳🇬'],
    ['code' => 'NL', 'name' => 'Netherlands', 'dial' => '+31', 'flag' => '🇳🇱'],
    ['code' => 'NP', 'name' => 'Nepal', 'dial' => '+977', 'flag' => '🇳🇵'],
    ['code' => 'PH', 'name' => 'Philippines', 'dial' => '+63', 'flag' => '🇵🇭'],
    ['code' => 'QA', 'name' => 'Qatar', 'dial' => '+974', 'flag' => '🇶🇦'],
    ['code' => 'RU', 'name' => 'Russia', 'dial' => '+7', 'flag' => '🇷🇺'],
    ['code' => 'SE', 'name' => 'Sweden', 'dial' => '+46', 'flag' => '🇸🇪'],
    ['code' => 'SG', 'name' => 'Singapore', 'dial' => '+65', 'flag' => '🇸🇬'],
    ['code' => 'TR', 'name' => 'Turkey', 'dial' => '+90', 'flag' => '🇹🇷'],
    ['code' => 'ZA', 'name' => 'South Africa', 'dial' => '+27', 'flag' => '🇿🇦'],
];

// Every other country, alphabetical: code => [name, dial]. Flag derived from code.
$rest = [
    'AF' => ['Afghanistan', '+93'],
    'AL' => ['Albania', '+355'],
    'DZ' => ['Algeria', '+213'],
    'AD' => ['Andorra', '+376'],
    'AO' => ['Angola', '+244'],
    'AG' => ['Antigua and Barbuda', '+1'],
    'AR' => ['Argentina', '+54'],
    'AM' => ['Armenia', '+374'],
    'AW' => ['Aruba', '+297'],
    'AT' => ['Austria', '+43'],
    'AZ' => ['Azerbaijan', '+994'],
    'BS' => ['Bahamas', '+1'],
    'BH' => ['Bahrain', '+973'],
    'BB' => ['Barbados', '+1'],
    'BY' => ['Belarus', '+375'],
    'BE' => ['Belgium', '+32'],
    'BZ' => ['Belize', '+501'],
    'BJ' => ['Benin', '+229'],
    'BT' => ['Bhutan', '+975'],
    'BO' => ['Bolivia', '+591'],
    'BA' => ['Bosnia and Herzegovina', '+387'],
    'BW' => ['Botswana', '+267'],
    'BN' => ['Brunei', '+673'],
    'BG' => ['Bulgaria', '+359'],
    'BF' => ['Burkina Faso', '+226'],
    'BI' => ['Burundi', '+257'],
    'KH' => ['Cambodia', '+855'],
    'CM' => ['Cameroon', '+237'],
    'CV' => ['Cape Verde', '+238'],
    'CF' => ['Central African Republic', '+236'],
    'TD' => ['Chad', '+235'],
    'CL' => ['Chile', '+56'],
    'CO' => ['Colombia', '+57'],
    'KM' => ['Comoros', '+269'],
    'CG' => ['Congo - Brazzaville', '+242'],
    'CD' => ['Congo - Kinshasa', '+243'],
    'CR' => ['Costa Rica', '+506'],
    'CI' => ['Côte d\'Ivoire', '+225'],
    'HR' => ['Croatia', '+385'],
    'CU' => ['Cuba', '+53'],
    'CY' => ['Cyprus', '+357'],
    'CZ' => ['Czechia', '+420'],
    'DK' => ['Denmark', '+45'],
    'DJ' => ['Djibouti', '+253'],
    'DM' => ['Dominica', '+1'],
    'DO' => ['Dominican Republic', '+1'],
    'EC' => ['Ecuador', '+593'],
    'SV' => ['El Salvador', '+503'],
    'GQ' => ['Equatorial Guinea', '+240'],
    'ER' => ['Eritrea', '+291'],
    'EE' => ['Estonia', '+372'],
    'SZ' => ['Eswatini', '+268'],
    'ET' => ['Ethiopia', '+251'],
    'FJ' => ['Fiji', '+679'],
    'FI' => ['Finland', '+358'],
    'GA' => ['Gabon', '+241'],
    'GM' => ['Gambia', '+220'],
    'GE' => ['Georgia', '+995'],
    'GH' => ['Ghana', '+233'],
    'GR' => ['Greece', '+30'],
    'GD' => ['Grenada', '+1'],
    'GT' => ['Guatemala', '+502'],
    'GN' => ['Guinea', '+224'],
    'GW' => ['Guinea-Bissau', '+245'],
    'GY' => ['Guyana', '+592'],
    'HT' => ['Haiti', '+509'],
    'HN' => ['Honduras', '+504'],
    'HK' => ['Hong Kong', '+852'],
    'HU' => ['Hungary', '+36'],
    'IS' => ['Iceland', '+354'],
    'IR' => ['Iran', '+98'],
    'IQ' => ['Iraq', '+964'],
    'IE' => ['Ireland', '+353'],
    'IL' => ['Israel', '+972'],
    'JM' => ['Jamaica', '+1'],
    'JO' => ['Jordan', '+962'],
    'KZ' => ['Kazakhstan', '+7'],
    'KE' => ['Kenya', '+254'],
    'KI' => ['Kiribati', '+686'],
    'XK' => ['Kosovo', '+383'],
    'KG' => ['Kyrgyzstan', '+996'],
    'LA' => ['Laos', '+856'],
    'LV' => ['Latvia', '+371'],
    'LB' => ['Lebanon', '+961'],
    'LS' => ['Lesotho', '+266'],
    'LR' => ['Liberia', '+231'],
    'LY' => ['Libya', '+218'],
    'LI' => ['Liechtenstein', '+423'],
    'LT' => ['Lithuania', '+370'],
    'LU' => ['Luxembourg', '+352'],
    'MO' => ['Macau', '+853'],
    'MG' => ['Madagascar', '+261'],
    'MW' => ['Malawi', '+265'],
    'MV' => ['Maldives', '+960'],
    'ML' => ['Mali', '+223'],
    'MT' => ['Malta', '+356'],
    'MH' => ['Marshall Islands', '+692'],
    'MR' => ['Mauritania', '+222'],
    'MU' => ['Mauritius', '+230'],
    'FM' => ['Micronesia', '+691'],
    'MD' => ['Moldova', '+373'],
    'MC' => ['Monaco', '+377'],
    'MN' => ['Mongolia', '+976'],
    'ME' => ['Montenegro', '+382'],
    'MA' => ['Morocco', '+212'],
    'MZ' => ['Mozambique', '+258'],
    'MM' => ['Myanmar', '+95'],
    'NA' => ['Namibia', '+264'],
    'NR' => ['Nauru', '+674'],
    'NZ' => ['New Zealand', '+64'],
    'NI' => ['Nicaragua', '+505'],
    'NE' => ['Niger', '+227'],
    'NO' => ['Norway', '+47'],
    'OM' => ['Oman', '+968'],
    'PW' => ['Palau', '+680'],
    'PS' => ['Palestine', '+970'],
    'PA' => ['Panama', '+507'],
    'PG' => ['Papua New Guinea', '+675'],
    'PY' => ['Paraguay', '+595'],
    'PE' => ['Peru', '+51'],
    'PL' => ['Poland', '+48'],
    'PT' => ['Portugal', '+351'],
    'PR' => ['Puerto Rico', '+1'],
    'RO' => ['Romania', '+40'],
    'RW' => ['Rwanda', '+250'],
    'KN' => ['Saint Kitts and Nevis', '+1'],
    'LC' => ['Saint Lucia', '+1'],
    'VC' => ['Saint Vincent and the Grenadines', '+1'],
    'WS' => ['Samoa', '+685'],
    'SM' => ['San Marino', '+378'],
    'ST' => ['São Tomé and Príncipe', '+239'],
    'SN' => ['Senegal', '+221'],
    'RS' => ['Serbia', '+381'],
    'SC' => ['Seychelles', '+248'],
    'SL' => ['Sierra Leone', '+232'],
    'SK' => ['Slovakia', '+421'],
    'SI' => ['Slovenia', '+386'],
    'SB' => ['Solomon Islands', '+677'],
    'SO' => ['Somalia', '+252'],
    'SS' => ['South Sudan', '+211'],
    'SD' => ['Sudan', '+249'],
    'SR' => ['Suriname', '+597'],
    'CH' => ['Switzerland', '+41'],
    'SY' => ['Syria', '+963'],
    'TW' => ['Taiwan', '+886'],
    'TJ' => ['Tajikistan', '+992'],
    'TZ' => ['Tanzania', '+255'],
    'TH' => ['Thailand', '+66'],
    'TL' => ['Timor-Leste', '+670'],
    'TG' => ['Togo', '+228'],
    'TO' => ['Tonga', '+676'],
    'TT' => ['Trinidad and Tobago', '+1'],
    'TN' => ['Tunisia', '+216'],
    'TM' => ['Turkmenistan', '+993'],
    'TV' => ['Tuvalu', '+688'],
    'UG' => ['Uganda', '+256'],
    'UA' => ['Ukraine', '+380'],
    'UY' => ['Uruguay', '+598'],
    'UZ' => ['Uzbekistan', '+998'],
    'VU' => ['Vanuatu', '+678'],
    'VA' => ['Vatican City', '+39'],
    'VE' => ['Venezuela', '+58'],
    'VN' => ['Vietnam', '+84'],
    'YE' => ['Yemen', '+967'],
    'ZM' => ['Zambia', '+260'],
    'ZW' => ['Zimbabwe', '+263'],
];

// ISO alpha-2 → flag emoji (two regional-indicator symbols).
$toFlag = fn (string $code): string => mb_convert_encoding('&#'.(127397 + ord($code[0])).';&#'.(127397 + ord($code[1])).';', 'UTF-8', 'HTML-ENTITIES');

$out = $popular;
$seen = array_column($popular, 'code');
foreach ($rest as $code => [$name, $dial]) {
    if (in_array($code, $seen, true)) {
        continue;
    }
    $out[] = ['code' => $code, 'name' => $name, 'dial' => $dial, 'flag' => $toFlag($code)];
}

return $out;
