<?php

/*
|--------------------------------------------------------------------------
| Which product each collected business category is a prospect for
|--------------------------------------------------------------------------
|
| Generated from the collector extension's src/data/categories.json, where
| the same mapping drives the category picker. Kept as config rather than a
| table because it changes when the product line changes, not with the data.
|
| Regenerate after editing categories.json so the two stay in step. Anything
| not listed here has no product fit and is scored as such.
|
*/

return [
    "Restaurant Management" => [
        "Bakery",
        "Bar",
        "Buffet restaurant",
        "Cafe",
        "Catering service",
        "Chinese restaurant",
        "Cloud kitchen",
        "Coffee shop",
        "Family restaurant",
        "Fast food restaurant",
        "Food court",
        "Ice cream shop",
        "Indian restaurant",
        "Pizza restaurant",
        "Pub",
        "Restaurant",
        "Sweet shop",
    ],
    "POS & Inventory" => [
        "Bag shop",
        "Book store",
        "Boutique",
        "Clothing store",
        "Computer store",
        "Convenience store",
        "Cosmetics store",
        "Department store",
        "Electronics store",
        "Furniture store",
        "Gift shop",
        "Grocery store",
        "Hardware store",
        "Jewelry store",
        "Mobile phone shop",
        "Optician",
        "Pet store",
        "Second hand shop",
        "Shoe store",
        "Sporting goods store",
        "Stationery store",
        "Supermarket",
        "Toy store",
        "Watch shop",
    ],
    "eCommerce" => [
        "Fabric store",
        "Florist",
        "Home goods store",
        "Perfume shop",
        "Wholesale market",
    ],
    "Pharmacy Management" => [
        "Medical equipment supplier",
        "Pharmacy",
    ],
    "Hospital Management" => [
        "Dental clinic",
        "Dentist",
        "Diagnostic centre",
        "Dialysis center",
        "Doctor",
        "Eye care center",
        "Hospital",
        "Maternity hospital",
        "Medical clinic",
        "Nursing home",
        "Pathology lab",
        "Veterinary clinic",
    ],
    "School Management" => [
        "Day care center",
        "High school",
        "Kindergarten",
        "Preschool",
        "Primary school",
        "School",
    ],
    "University Management" => [
        "College",
        "University",
        "Vocational school",
    ],
    "LMS & Training" => [
        "Art school",
        "Coaching center",
        "Computer training institute",
        "Driving school",
        "Exam preparation centre",
        "Language school",
        "Music school",
        "Training center",
        "Tutoring service",
    ],
    "Laundry Management" => [
        "Dry cleaning service",
        "Ironing service",
        "Laundry",
    ],
    "Ride Sharing" => [
        "Ambulance service",
        "Bus operator",
        "Car rental",
        "Taxi service",
        "Transport service",
    ],
    "On-Demand Services" => [
        "Air conditioning service",
        "Appliance repair service",
        "Barber shop",
        "Beauty salon",
        "Carpenter",
        "Cleaning service",
        "Electrician",
        "Hair salon",
        "Massage therapist",
        "Moving company",
        "Nail salon",
        "Pest control service",
        "Plumber",
        "Spa",
    ],
    "Garments Management" => [
        "Embroidery service",
        "Fabric wholesaler",
        "Garment factory",
        "Tailor",
        "Textile mill",
    ],
    "ERP & Manufacturing" => [
        "Cement supplier",
        "Chemical supplier",
        "Cold storage",
        "Distributor",
        "Factory",
        "Freight forwarder",
        "Industrial equipment supplier",
        "Logistics service",
        "Machinery supplier",
        "Manufacturer",
        "Packaging supplier",
        "Plastic manufacturer",
        "Steel supplier",
        "Warehouse",
    ],
    "Wellness & Meditation" => [
        "Fitness center",
        "Gym",
        "Meditation centre",
        "Sports club",
        "Wellness center",
        "Yoga studio",
    ],
    "AI & Digital Solutions" => [
        "Advertising agency",
        "Digital marketing agency",
        "Event planner",
        "Guest house",
        "Hotel",
        "IT services",
        "Marketing agency",
        "Photo studio",
        "Real estate agency",
        "Resort",
        "Software company",
        "Travel agency",
        "Web designer",
    ],
];
